### ISSUE TITLE
Minimize Github API access

### ISSUE THREAD

**Issue by Hofer-Julian** [bearcove/feedback#220]
When trying to connect fasterthanli.me with my Github, I saw that it would give you read access to organization data.
I might be naive there, but I've hoped that you can verify me without this kind of data.
I assume many companies will not be fond of their private project boards leaking that way.

![image](https://github.com/fasterthanlime/feedback/assets/30049909/0caf3405-5872-49c0-8bbf-6b42df24ddaa)

**Comment by fasterthanlime** [comment]
The "private project boards" thing (and wording) is news to me.

I /think/ the reasoning is that I needed to be able to query if an organisation you're a part of is sponsoring me to grant you the early access bonus?

I can probably make this opt-in though (at the very least) so it only asks for it, if it finds you don't support me directly. (Or maybe organisations supporting me shouldn't give access to all their members anyway..)

I'll definitely take a look at this (no ETA guarantees, but I agree this looks fishy)

**Comment by fasterthanlime** [comment]
I've deployed a version of the codebase that only asks for `user:read`. I think `org:read` was a mistake and never needed.

I've also deleted all records from the `github_credentials` table:

```
app=# delete from github_credentials;
DELETE 835
app=#
```

...which means I don't have "too-powerful" credentials in my DB anymore and can't accidentally use them.

⚠️ **However, if me, or someone with my OAuth credentials, were malicious, they _still_ could obtain tokens with `org:read` permissions, because GitHub remembers consent was given.**

To reset this:

  * Go to https://github.com/settings/applications
  * Scroll to `fasterthanli.me`
  * Hit the three-dots menu
  * Click `Revoke`
  * Click `I understand, revoke access`

(This doesn't delete your user settings on fasterthanli.me.)

After that, Log out and Log into fasterthanli.me again. Hopefully everything still works!

---

New flow:

<img width="621" alt="github login screen showing only read-only access to user data" src="https://github.com/fasterthanlime/feedback/assets/7998310/05a6adb9-ef42-4907-a719-531a3b486a4b">

<img width="603" alt="same image but the user bit is expanded and has a link to github docs" src="https://github.com/fasterthanlime/feedback/assets/7998310/a43ecdd9-adee-40e8-9524-8bb31e0ec39e">

`/profile` shows your access level:

<img width="1191" alt="screenshot of my site, I have creator tier" src="https://github.com/fasterthanlime/feedback/assets/7998310/257fe556-5533-4295-9058-e5ee96ed9a44">

---

Thanks for catching this!

**Comment by fasterthanlime** [comment]
Okay, so the mystery is now _fully_ solved: the scope _was_ useful, but only for me!

I run a different set of GraphQL queries to generate the list at https://fasterthanli.me/patron-list - and those require the `read:org` scope.

I simply added code that asks me (and only me) to re-log in with broader scopes when I log in with GitHub.
