### ISSUE TITLE
A half-hour to learn Rust

### ISSUE THREAD

**Issue by StefanSalewski** [bearcove/feedback#280]
I found something wrong on this page:

  https://fasterthanli.me/articles/a-half-hour-to-learn-rust#position=17.9

  Here's what it is:

Hello. After reading the official free Rust book in the last weeks, I just studied your page "https://fasterthanli.me/articles/a-half-hour-to-learn-rust" for a short recap. But I can not understand these two examples:

```
let v = Vec2 { x: 3.0, y: 6.0 };
let Vec2 { x, y } = v;
// `x` is now 3.0, `y` is now `6.0`
```

```
let Vec2 { x, .. } = v;
// this throws away `v.y`
```

Line two in first example, and first line in second example makes no sense for me. Seems not even to compile, and if it would compile, what is the actual use case. Was that valid code in older Rust releases, or is it a typo?

It is really interesting to see a tutorial page where one can easily post questions and issues.

Best regards,

Dr. Stefan Salewski

**Comment by wonderfulspam** [comment]
> Seems not even to compile

It compiles and runs just fine: [Rust Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9610ca3d7bd8a847c7c208d9b5ca3fa8)

> what is the actual use case

If you are only interested in one of the values but destructure both, the compiler will yell at you for having an unused variable. You can try removing the `println!` statements in the Playground link to see what happens. You could of course directly reference `v.x` instead of destructuring and throwing away `y`, but Rust favours an explicit style of programming where you use patterns like destructuring to clarify your intent.

Imagine you are calling a function that returns a large struct which has only two fields that you care about. By explicitly declaring these fields at the callsite, you are expressing your intent. This makes refactoring easier and improves code locality, ie. being able to see which fields will be used without having to read the rest of the function. [This Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2201b65dff5f87bdd51598f1045fafdf) shows a very contrived example of that.

That said, partial struct destructuring is a rather niche pattern. You'll see partial destructuring come up more frequently with tuples like in the `split_at` example given in the blog post.

**Comment by StefanSalewski** [comment]
Thank you very much for your detailed explanation. Now I do understand this "unpacking" syntax. Actually, I tried that code in the Rust playground yesterday, but I think I forgot to put the code inside of a main() function and so got some error messages. I will close this issue now.

Best regards,

Dr. Stefan Salewski
