### ISSUE TITLE
Multiline <code> element in lynx shows up as a single line

### ISSUE THREAD

**Issue by epurcell3** [bearcove/feedback#4]
**Where's the problem at?**
`<code>` elements don't respect new lines in lynx, but should when wrapped with a `<pre>` element (per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes)). 

**An Example**
The first shell session `<code>` block of https://fasterthanli.me/series/making-our-own-executable-packer/part-14. Open it in the lynx browser and on page two (for my laptop's resolution, might be different for others) there's a semi-comprehensible block of text `lynx https://fasterthanli.me/series/making-our-own-executable-packer/part-14`.

**Describe the issue and a fix if you know it**
Due to lynx's (and the spec's as I understand MDN's understanding) of `<code>` blocks, outside of a `<pre>` block it assumes it's a short single line code block, which ignores new lines and makes a mess of your `<code>` blocks. Firefox (somehow) accepts your new lines, but lynx does not.

**Comment by fasterthanlime** [comment]
So this is caused by a "fix" I did for edbrowse, a line-oriented browser http://edbrowse.org/ (even nicher than lynx/links!)

edbrowse complained about `<div>` tags nested in `<pre>`, as it should (it's invalid HTML5), so I changed the `<pre>` to `<div class="pre-like">` and set css rule `white-space: pre`, which I'm guessing lynx/links do not support.

I can think of ways to fix it that would work in lynx, thanks for the report!

**Comment by fasterthanlime** [comment]
I've deployed a fix for lynx, looks okay for me now:

![image](https://user-images.githubusercontent.com/7998310/162958100-5e375323-2958-495f-aea5-0a82fea4673c.png)

Hopefully that didn't break edbrowse!

**Comment by epurcell3** [comment]
Just built edbrowse to check for you and everything seems to look alright in edbrowse as well, though I can't say I'm very familiar with it or if this fix is compatible with whatever version of edbrowse the other issue was using.

**Comment by fasterthanlime** [comment]
Haha, thanks so much for checking edbrowse!
